Repository uktrade/trade-tariff-management, pull requests merged in 2019-10, with the labels that each got.

#473 Fix: Allow Measures to use types with future start date.
  app/models/measure.rb
  app/models/measure_type.rb
  app/validators/measure_validator.rb
  app/views/workbaskets/create_regulation/steps/main/_regulation_identifier.html.slim
  lib/sequel/plugins/time_machine.rb
Labels: help wanted

#477 Hide 'Remove Period' if there’s only 1 custom period
  app/views/shared/vue_templates/_quota_section.html.erb
  db/structure.sql
Labels: fix

#480 Fix wrong heading copy
  app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
Labels: fix

#484 Fix 'Edit footnote' link
  app/views/workbaskets/create_footnote/show.html.slim
  app/views/workbaskets/edit_footnote/show.html.slim
Labels: fix

#485 Fix find form links
  app/views/additional_codes/additional_codes/_search_form.html.erb
  app/views/certificates/certificates/search/_form.html.slim
  app/views/footnotes/footnotes/search/_form.html.slim
  app/views/geo_areas/geo_areas/search/_form.html.slim
  app/views/measures/bulks/_action_buttons.html.slim
  app/views/measures/measures/_search_form.html.erb
  app/views/quotas/bulks/_action_buttons.html.slim
  app/views/quotas/quotas/_search_form.html.erb
  app/views/regulations/search/_form.html.slim
  app/views/shared/bulks/_action_buttons.html.slim
  app/views/workbaskets/create_additional_code/_action_links.html.slim
  app/views/workbaskets/create_certificate/_action_links.slim
  app/views/workbaskets/create_footnote/_action_links.html.slim
  app/views/workbaskets/create_geographical_area/_action_links.html.slim
  app/views/workbaskets/create_measures/show.html.slim
  app/views/workbaskets/create_quota/show.html.slim
  app/views/workbaskets/create_regulation/_action_links.html.slim
  app/views/workbaskets/edit_certificate/_action_links.html.slim
  app/views/workbaskets/edit_footnote/_action_links.html.slim
  app/views/workbaskets/edit_geographical_area/_action_links.html.slim
  app/views/workbaskets/edit_nomenclature/_action_links.html.slim
  app/views/workbaskets/manage_nomenclatures/new.html.erb
  app/views/workbaskets/shared/_action_links.html.slim
  app/views/workbaskets/workflows/approves/_action_links.html.slim
  app/views/workbaskets/workflows/cross_checks/_action_links.html.slim
Labels: enhancement, fix

#487 Fix view footnote breadcrumb
  app/views/workbaskets/create_footnote/show.html.slim
  app/views/workbaskets/edit_footnote/show.html.slim
Labels: fix

#489 Update breadcrumbs
  README.md
  app/helpers/approval_helper.rb
  app/helpers/cross_check_helper.rb
  app/views/additional_codes/bulks/show.html.slim
  app/views/measures/bulks/edit.html.slim
  app/views/measures/bulks/work_with_selected_measures.html.erb
  app/views/regulations/index.html.slim
  app/views/workbaskets/bulk_edit_of_measures/show.html.slim
  app/views/workbaskets/create_additional_code/_breadcrumbs.html.slim
  app/views/workbaskets/create_certificate/show.html.slim
  app/views/workbaskets/create_footnote/show.html.slim
  app/views/workbaskets/create_geographical_area/show.html.slim
  app/views/workbaskets/create_measures/show.html.slim
  app/views/workbaskets/create_quota/_breadcrumbs.html.slim
  app/views/workbaskets/create_quota/show.html.slim
  app/views/workbaskets/edit_certificate/show.html.slim
  app/views/workbaskets/edit_footnote/show.html.slim
  app/views/workbaskets/edit_geographical_area/show.html.slim
  app/views/workbaskets/edit_regulation/show.html.slim
  spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb
Labels: enhancement, fix

#490 Fix validation on create additional codes
  app/assets/javascripts/components/validators/additional_codes.js
  app/interactors/workbasket_interactions/create_additional_code/settings_saver.rb
  app/views/workbaskets/create_additional_code/steps/main/_additional_codes.html.slim
  app/views/workbaskets/create_additional_code/steps/main/_start_end_dates.html.slim
Labels: fix

#495 Fix withdraws links not showing bug
  app/helpers/workbasket_workflow_helper.rb
Labels: fix

#500 Fix edit quotas link options on submission
  app/controllers/quotas/bulks_controller.rb
  app/helpers/workbasket_helper.rb
  app/views/quotas/bulks/submitted_for_cross_check.html.slim
Labels: bug, fix

#501 Fix return to main menu links on create regulation
  app/views/shared/bulks/_action_buttons.html.slim
  app/views/workbaskets/create_regulation/show.html.slim
Labels: fix

#503 Fix regulations view page data
  app/views/workbaskets/create_regulation/show.html.slim
  app/views/workbaskets/create_regulation/steps/review_and_submit/_details.html.slim
  app/views/workbaskets/create_regulation/steps/review_and_submit/_message.html.slim
  app/views/workbaskets/create_regulation/workflow_screens_parts/notifications/_block.html.slim
Labels: fix

#506 Fix section data persistence
  app/assets/javascripts/components/quota-form.js
  app/assets/javascripts/vue_components/date-gds.js
  app/assets/javascripts/vue_components/quota-section.js
  app/assets/javascripts/vue_components/quota-sections-manager.js
  app/views/shared/vue_templates/_quota_section.html.erb
  spec/features/workbasket/quota/quota_creation_validations_spec.rb
  spec/features/workbasket/quota/quota_spec.rb
Labels: fix

#507 Remove duplicate edit links
  app/views/workbaskets/create_regulation/show.html.slim
  app/views/workbaskets/edit_regulation/show.html.slim
Labels: fix

#508 Use date-gds at find certificates
  app/views/certificates/certificates/search/_form.html.slim
Labels: fix

#509 Fix validation bugs on create additional codes
  app/assets/javascripts/components/validators/additional_codes.js
Labels: fix

#513 Fix headings on show pages
  app/views/additional_codes/bulks/show.html.slim
  app/views/quotas/bulks/show.html.slim
Labels: fix

#515 Fix title heading
  app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim
Labels: fix

#514 Remove not reuqired message from review page
  app/views/workbaskets/create_regulation/steps/_review_and_submit.html.slim
Labels: fix

#522 Fix confirmation messages
  app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
  app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
  app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
  app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
  app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
  app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_approval_rejected.html.slim
  app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
  app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
  app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_certificate/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_geographical_area/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
  app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
  app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/create_quota_association/workflow_screens_parts/status_pages/_approval_rejected.html.slim
  app/views/workbaskets/create_quota_association/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/edit_certificate/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
  app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_approval_rejected.html.slim
  app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
Labels: enhancement, fix

#523 Add missing link to quota show page
  app/views/workbaskets/create_quota_association/show.html.slim
Labels: fix

#524 Add missing withdraw links
  app/views/workbaskets/edit_nomenclature/show.html.erb
  app/views/workbaskets/edit_regulation/show.html.slim
  app/views/workbaskets/edit_regulation/workflow_screens_parts/_actions_allowed.html.slim
Labels: fix

#527 Hide locked column on record grid on demand
  app/assets/javascripts/vue_components/records-grid.js
  app/views/shared/vue_templates/_records_grid.html.erb
  app/views/workbaskets/create_additional_code/show.html.slim
Labels: enhancement

#531 Fix heading on bulk additional codes show page
  app/views/additional_codes/bulks/edit.html.slim
Labels: fix

#530 Add Link to Main menu to Create reference documents
  .circleci/config.yml
  app/views/workbaskets/main_menu_parts/_main_menu.html.slim
Labels: enhancement

#532 Fix quota associations create breadcrumbs
  app/helpers/workbasket_workflow_helper.rb
  app/views/workbaskets/create_quota_association/edit.html.erb
  app/views/workbaskets/create_quota_association/show.html.slim
Labels: fix

#534 Fix records grid client sorting
  app/assets/javascripts/vue_components/records-grid.js
Labels: fix
